---
name: Build
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    

jobs:
  analyze:
    name: Analyze
    runs-on: elvia-runner
    permissions:
      actions: read
      contents: read
      security-events: write
    # if: github.ref != 'refs/heads/master' # only run analyze on PR
    steps:
      - uses: 3lvia/core-github-actions-templates/analyze@trunk
        with:
          language: go

  build:
    name: Build and Scan
    runs-on: elvia-runner
    environment: build
    permissions:
      actions: read
      contents: write
      id-token: write
      pull-requests: write
      security-events: write
    steps:
      - uses: 3lvia/core-github-actions-templates/build@trunk
        with:
          name: kafka-exporter
          namespace: monitoring
          dockerfile: Dockerfile
          registry: ghcr.io/3lvia
