---
name: Build
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    

jobs:
  analyze:
    name: Analyze
    runs-on: elvia-runner
    # if: github.ref != 'refs/heads/master' # only run analyze on PR
    steps:
      - uses: 3lvia/core-github-actions-templates/analyze@trunk
        with:
          language: go

  build:
    name: Build and Scan
    runs-on: elvia-runner
    environment: build
    steps:
      - uses: 3lvia/core-github-actions-templates/build@trunk
        with:
          name: github-metrics
          namespace: monitoring
          dockerfile: Dockerfile
          registry: ghcr.io/3lvia
